#!/usr/bin/env python

import os
import shutil
from diffusers import StableDiffusionPipeline
from diffusers.pipelines.stable_diffusion.safety_checker import (
    StableDiffusionSafetyChecker,
)
import torch

MODEL_ID = "pagebrain/$MODEL_NAME"
MODEL_CACHE = "diffusers-cache"

# if os.path.exists(MODEL_CACHE):
#     shutil.rmtree(MODEL_CACHE)
# os.makedirs(MODEL_CACHE, exist_ok=True)

saftey_checker = StableDiffusionSafetyChecker.from_pretrained(
    "./model/safety_checker",
    # cache_dir=MODEL_CACHE,
    # use_safetensors=True
    torch_dtype=torch.float16,
)

pipe = StableDiffusionPipeline.from_pretrained(
    "./model",
    # cache_dir=MODEL_CACHE,
    use_safetensors=True,
    safety_checker=None
)
